# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Subject.destroy_all
Review.destroy_all
Vote.destroy_all

# User.reset_pk_sequence
# Subject.reset_pk_sequence
# Review.reset_pk_sequence
# Vote.reset_pk_sequence



# Users:
user1 = User.create(username: "razajafri")
user2 = User.create(username: "derickcastillo")
user3 = User.create(username: "ethandavidson")
user4 = User.create(username: "yusufcelep")
user5 = User.create(username: "adamshaffer")
user6 = User.create(username: "ellisandrews")
user7 = User.create(username: "jasonmelton")
user8 = User.create(username: "davideber")
user9 = User.create(username: "jackoverby")
user10 = User.create(username: "mikepottebaum")


# Subjects:
subject1 = Subject.create(description: "Common Business-Oriented Language, widely used in legacy applications", category: "Programming Languages", name: "COBOL")
subject2 = Subject.create(description: "An open-ended social simulation video game from Nintendo featuring anthropomorphic animals", category: "Gaming", name: "Animal Crossing")
subject3 = Subject.create(description: "A Netflix documentary miniseries about the life and felonies of animal keeper Joe Exotic", category: "Television", name: "Tiger King")
subject4 = Subject.create(description: "A scientist turns invisible and attempts to kill his wife", category: "Movies", name: "The Invisible Man")
subject5 = Subject.create(description: "Telling jokes to an audience", category: "Humor", name: "Stand-up comedy")
subject6 = Subject.create(description: "A virus currently causing worldwide pandemic", category: "News and Issues", name: "Covid-19")
subject7 = Subject.create(description: "Entertainment", category: "Sports", name: "Basketball")
subject8 = Subject.create(description: "Entertainment", category: "Sports", name: "Wrestling")
subject9 = Subject.create(description: "Post-punk band fronted by David Byrne", category: "Music", name: "The Talking Heads")
subject10 = Subject.create(description: "HBO series focusing on the life, family, and inner circle of mob boss Tony Soprano", category: "Television", name: "The Sopranos")
subject11 = Subject.create(description: "Interpreted, high-level, general purpose programming language popularized by the Rails web application framework", category: "Programming Languages", name: "Ruby")
subject12 = Subject.create(description: "High-level dynamically typed language commonly used for client-side web development", category: "Programming Languages", name: "JavaScript")
subject13 = Subject.create(description: "Statically typed, compiled memory-safe language with both low and high-level uses", category: "Programming Languages", name: "Rust")



# Reviews:
review1 = Review.create(content: "Programming is not a personality trait.", subject_id: 1, user_id: 7, score: 3)
review2 = Review.create(content: "COBOL really picked up during this crisis.", subject_id: 1, user_id: 3, score: 4)
review3 = Review.create(content: "COBOL reserves the first 6 columns for numbering. This gives the possibility of 999,999 lines of code. What happens when a COBOL program reaches 1 million lines?", subject_id: 1, user_id: 10, score: 2)
review4 = Review.create(content: "Animal Crossing: New Horizons just came out!", subject_id: 2, user_id: 1, score: 5)
review5 = Review.create(content: "Workbenches in our houses should be able to access storage.", subject_id: 2, user_id: 4, score: 3)
review6 = Review.create(content: "Protip: Keep a few stacks of Earth Eggs and bury them on your friend's islands so they can experience the magic of Bunny Day all year round. :D", subject_id: 2, user_id: 8, score: 3)
review7 = Review.create(content: "Is the Tiger King trend still on?", subject_id: 3, user_id: 2, score: 4)
review8 = Review.create(content: "When you get to the part in Tiger King where all of Rick's footage is lost in a fire, after you've just watched hours of it", subject_id: 3, user_id: 6, score: 5)
review9 = Review.create(content: "It's definitely harder to be a woman. Joe Exotic lured straight men into homosexuality with meth, sold tigers on the black market, and he cared more about his financial security than his employee losing an arm and I'm still like 'Fuck Carole Baskin.'", subject_id: 3, user_id: 9, score: 5)
review10 = Review.create(content: "Yo that was wack", subject_id: 4, user_id: 5, score: 4)
review11 = Review.create(content: "That was smart of her when she poured paint over him in that one scene. Finally some common sense.", subject_id: 4, user_id: 2, score: 4)
review12 = Review.create(content: "My kid came up with a blank leaf of paper saying they 'drew' the invisible man.", subject_id: 4, user_id: 10, score: 3)
review13 = Review.create(content: "I loved the 'Man feels eye pain exactly 45 seconds after reading it's a coronavirus symptom' joke", subject_id: 5, user_id: 4, score: 4)
review14 = Review.create(content: "The people who avoid Corona beer are the same people who belive chocolate milk comes from brown cows.", subject_id: 5, user_id: 8, score: 5)
review15 = Review.create(content: "How would Van Gogh have worn his mask though?", subject_id: 5, user_id: 7, score: 4)
review16 = Review.create(content: "Body-bag stocks are running out, suppliers say.", subject_id: 6, user_id: 5, score: 3)
review17 = Review.create(content: "US Postal Service says it will run out of money by September", subject_id: 6, user_id: 1, score: 2)
review18 = Review.create(content: "AMC Theatres reportedly in talks with Bankruptcy Lawyers", subject_id: 6, user_id: 3, score: 2)
review19 = Review.create(content: "Kobe Bryant posthumously elected to Basketball Hall of Fame", subject_id: 7, user_id: 6, score: 5)
review20 = Review.create(content: "Are you surprised by the amount of sexism the NBA instagram comments have right now?", subject_id: 7, user_id: 9, score: 1)
review21 = Review.create(content: "NBA owner, and Houston billionaire, lays off 45,000 employees as 'a favor' to them during coronavirus pandemic", subject_id: 7, user_id: 1, score: 2)
review22 = Review.create(content: "NCAA Tournament officially canceled", subject_id: 8, user_id: 3, score: 1)
review23 = Review.create(content: "Fun Fact: Turkey's National Sport is Oil Wrestling!", subject_id: 8, user_id: 5, score: 5)
review24 = Review.create(content: "Florida Governor: WWE is an 'essential business'", subject_id: 8, user_id: 8, score: 3)
review25 = Review.create(content: "The Talking Heads - Stop Making Sense - possibly the greatest concert film", subject_id: 9, user_id: 2, score: 5)
review26 = Review.create(content: "Vans releasing sneaker inspired by Talking Heads", subject_id: 9, user_id: 9, score: 3)
review27 = Review.create(content: "Does anyone think Talking Heads are criminally underrated?", subject_id: 9, user_id: 10, score: 5)
review28 = Review.create(content: "Should I make a blog about The Sopranos?", subject_id: 10, user_id: 7, score: 4)
review29 = Review.create(content: "Not that it matters, but Rolling Stone Magazine ranked The Sopranos as the Best TV Show of All Time.", subject_id: 10, user_id: 6, score: 4)
review30 = Review.create(content: "I just watched The Sopranos for the second time all the way through, and I think James Gandolfini's performance is the best acting job in a television show of all time.", subject_id: 10, user_id: 4, score: 5)
review31 = Review.create(content: "ActiveSupport is so awesome", subject_id: 11, user_id: 1, score: 5)
review32 = Review.create(content: "My new gem: Heya is a campaign mailer for Rails", subject_id: 11, user_id: 2, score: 4)
review33 = Review.create(content: "God, I want to hit my head against this wall, what black magic is this", subject_id: 11, user_id: 3, score: 1)
review34 = Review.create(content: "Any fans of JavaScript on hardware? I wanted to share an IoT device I made that tells me when my next bus will arrive", subject_id: 12, user_id: 4, score: 3)
review35 = Review.create(content: "I don't know where I'd be without Stack Overflow, my job title should be professional google searcher instead of developer", subject_id: 12, user_id: 5, score: 3)
review36 = Review.create(content: "if JavaScript had a personality it would be the street-wise teenager who lurks in the web-covered side streets; helping the occasional passerby make sense of the road signs and stopping them from taking one way streets in the wrong direction. He has two dogs called HTML and CSS that he and his beautiful girlfriend (named JQuery) groom and train to do tricks with one another.", subject_id: 12, user_id: 6, score: 4)
review37 = Review.create(content: "Rust is clearly superior to C++", subject_id: 13, user_id: 7, score: 5)
review38 = Review.create(content: "I can't keep up with idiomatic Rust", subject_id: 13, user_id: 8, score: 3)
review39 = Review.create(content: "I can't think anymore, my brains fried", subject_id: 13, user_id: 9, score: 1)


# Votes:
vote1 = Vote.create(review_id: 1, user_id: 1, sentiment: -1)
vote2 = Vote.create(review_id: 14, user_id: 1, sentiment: 1)
vote3 = Vote.create(review_id: 24, user_id: 1, sentiment: 1)
vote4 = Vote.create(review_id: 30, user_id: 1, sentiment: 1)
vote5 = Vote.create(review_id: 9, user_id: 1, sentiment: -1)
vote6 = Vote.create(review_id: 4, user_id: 1, sentiment: -1)
vote7 = Vote.create(review_id: 5, user_id: 1, sentiment: 1)
vote8 = Vote.create(review_id: 17, user_id: 1, sentiment: -1)
vote9 = Vote.create(review_id: 18, user_id: 1, sentiment: 1)
vote10 = Vote.create(review_id: 15, user_id: 2, sentiment: 1)
vote11 = Vote.create(review_id: 7, user_id: 2, sentiment: 1)
vote12 = Vote.create(review_id: 6, user_id: 2, sentiment: 1)
vote13 = Vote.create(review_id: 3, user_id: 2, sentiment: -1)
vote14 = Vote.create(review_id: 2, user_id: 2, sentiment: 1)
vote15 = Vote.create(review_id: 12, user_id: 2, sentiment: -1)
vote16 = Vote.create(review_id: 20, user_id: 2, sentiment: 1)
vote17 = Vote.create(review_id: 16, user_id: 2, sentiment: 1)
vote18 = Vote.create(review_id: 27, user_id: 2, sentiment: 1)
vote19 = Vote.create(review_id: 10, user_id: 3, sentiment: 1)
vote20 = Vote.create(review_id: 21, user_id: 3, sentiment: 1)
vote21 = Vote.create(review_id: 29, user_id: 3, sentiment: -1)
vote22 = Vote.create(review_id: 8, user_id: 3, sentiment: 1)
vote23 = Vote.create(review_id: 19, user_id: 3, sentiment: 1)
vote24 = Vote.create(review_id: 11, user_id: 3, sentiment: 1)
vote25 = Vote.create(review_id: 25, user_id: 3, sentiment: -1)
vote26 = Vote.create(review_id: 22, user_id: 3, sentiment: -1)
vote27 = Vote.create(review_id: 13, user_id: 3, sentiment: 1)
vote28 = Vote.create(review_id: 26, user_id: 4, sentiment: -1)
vote29 = Vote.create(review_id: 23, user_id: 4, sentiment: 1)
vote30 = Vote.create(review_id: 28, user_id: 4, sentiment: 1)
vote31 = Vote.create(review_id: 5, user_id: 4, sentiment: 1)
vote32 = Vote.create(review_id: 17, user_id: 4, sentiment: -1)
vote33 = Vote.create(review_id: 28, user_id: 4, sentiment: 1)
vote34 = Vote.create(review_id: 18, user_id: 4, sentiment: -1)
vote35 = Vote.create(review_id: 1, user_id: 4, sentiment: 1)
vote36 = Vote.create(review_id: 3, user_id: 4, sentiment: 1)
vote37 = Vote.create(review_id: 8, user_id: 5, sentiment: 1)
vote38 = Vote.create(review_id: 19, user_id: 5, sentiment: 1)
vote39 = Vote.create(review_id: 27, user_id: 5, sentiment: -1)
vote40 = Vote.create(review_id: 7, user_id: 5, sentiment: 1)
vote41 = Vote.create(review_id: 2, user_id: 5, sentiment: 1)
vote42 = Vote.create(review_id: 26, user_id: 5, sentiment: 1)
vote43 = Vote.create(review_id: 30, user_id: 5, sentiment: 1)
vote44 = Vote.create(review_id: 16, user_id: 5, sentiment: -1)
vote45 = Vote.create(review_id: 11, user_id: 5, sentiment: -1)
vote46 = Vote.create(review_id: 21, user_id: 6, sentiment: 1)
vote47 = Vote.create(review_id: 15, user_id: 6, sentiment: -1)
vote48 = Vote.create(review_id: 6, user_id: 6, sentiment: -1)
vote49 = Vote.create(review_id: 20, user_id: 6, sentiment: 1)
vote50 = Vote.create(review_id: 10, user_id: 6, sentiment: 1)
vote51 = Vote.create(review_id: 29, user_id: 6, sentiment: 1)
vote52 = Vote.create(review_id: 13, user_id: 6, sentiment: -1)
vote53 = Vote.create(review_id: 22, user_id: 6, sentiment: 1)
vote54 = Vote.create(review_id: 4, user_id: 6, sentiment: 1)
vote55 = Vote.create(review_id: 9, user_id: 7, sentiment: 1)
vote56 = Vote.create(review_id: 14, user_id: 7, sentiment: 1)
vote57 = Vote.create(review_id: 12, user_id: 7, sentiment: 1)
vote58 = Vote.create(review_id: 25, user_id: 7, sentiment: -1)
vote59 = Vote.create(review_id: 23, user_id: 7, sentiment: 1)
vote60 = Vote.create(review_id: 24, user_id: 7, sentiment: 1)
vote61 = Vote.create(review_id: 22, user_id: 7, sentiment: 1)
vote62 = Vote.create(review_id: 5, user_id: 7, sentiment: -1)
vote63 = Vote.create(review_id: 2, user_id: 7, sentiment: 1)
vote64 = Vote.create(review_id: 3, user_id: 8, sentiment: -1)
vote65 = Vote.create(review_id: 26, user_id: 8, sentiment: 1)
vote66 = Vote.create(review_id: 16, user_id: 8, sentiment: 1)
vote67 = Vote.create(review_id: 15, user_id: 8, sentiment: 1)
vote68 = Vote.create(review_id: 30, user_id: 8, sentiment: 1)
vote69 = Vote.create(review_id: 4, user_id: 8, sentiment: -1)
vote70 = Vote.create(review_id: 6, user_id: 8, sentiment: 1)
vote71 = Vote.create(review_id: 10, user_id: 8, sentiment: 1)
vote72 = Vote.create(review_id: 19, user_id: 8, sentiment: 1)
vote73 = Vote.create(review_id: 17, user_id: 9, sentiment: 1)
vote74 = Vote.create(review_id: 1, user_id: 9, sentiment: -1)
vote75 = Vote.create(review_id: 14, user_id: 9, sentiment: -1)
vote76 = Vote.create(review_id: 23, user_id: 9, sentiment: 1)
vote77 = Vote.create(review_id: 8, user_id: 9, sentiment: -1)
vote78 = Vote.create(review_id: 7, user_id: 9, sentiment: -1)
vote79 = Vote.create(review_id: 21, user_id: 9, sentiment: 1)
vote80 = Vote.create(review_id: 29, user_id: 9, sentiment: 1)
vote81 = Vote.create(review_id: 13, user_id: 9, sentiment: 1)
vote82 = Vote.create(review_id: 11, user_id: 10, sentiment: -1)
vote83 = Vote.create(review_id: 12, user_id: 10, sentiment: 1)
vote84 = Vote.create(review_id: 18, user_id: 10, sentiment: 1)
vote85 = Vote.create(review_id: 25, user_id: 10, sentiment: 1)
vote86 = Vote.create(review_id: 24, user_id: 10, sentiment: 1)
vote87 = Vote.create(review_id: 27, user_id: 10, sentiment: 1)
vote88 = Vote.create(review_id: 28, user_id: 10, sentiment: -1)
vote89 = Vote.create(review_id: 9, user_id: 10, sentiment: 1)
vote90 = Vote.create(review_id: 20, user_id: 10, sentiment: 1)